gui:
  screenMode: "normal"
  nerdFontsVersion: 3
  border: "single"
  sidePanelWidth: 0.3
  showCommandLog: false
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: "nvim"
promptToReturnFromSubprocess: false
