gui:
  windowSize: "normal"
  nerdFontsVersion: 3
  border: "single"
  sidePanelWidth: 0.3
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: "nvim"
